language: php

services:
  - memcached

php:
  - "7.0"
  - "5.6"

install:
  - sudo apt-get install libmemcached libmemcached-dev
  - printf "\n" | pecl install -f memcached
  - composer install

script: 
  - phpunit
